#!/bin/sh

if [ $# -lt 1 ]; then
  echo 'First positional argument shall be a path to colcon work space'
  exit 1
fi

INITIAL_DIR=$(pwd)
if cd "$1"; then
  shift 1
  colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -Wno-error $@
  cd $INITIAL_DIR
else
  echo "Could not enter the directory: $1"
  exit 1
fi
