#!/bin/sh

set -e

if ! command -v curl > /dev/null 2>&1; then
  echo 'No curl found'
  exit 1
fi

url=https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-x86_64.tar.xz
tmp="/tmp/zen.tar.gz"
echo 'Downloading newset version'
curl -L -o $tmp $url
echo 'Installing newest version'
sudo tar -xf $tmp -C /opt
echo 'Cleaning up'
rm -rf $tmp

sudo ln -s /opt/zen/zen /usr/bin/zen
sudo mkdir -p /usr/local/share/applications/
cat <<EOF
[Desktop Entry]
Version=1.0
Name=Zen Browser
Comment=Experience tranquillity while browsing the web without people tracking you!
GenericName=Web Browser
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=zen
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/opt/zen/browser/chrome/icons/default/default128.png
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
EOF > /usr/local/share/applications/zen.desktop

echo 'Done'