#!/bin/sh

set -e

if [ ! command -v curl ]; then
  echo 'No curl found'
  exit 1
fi

url="https://github.com/eza-community/eza/releases/download/v0.21.4/eza_x86_64-unknown-linux-gnu.tar.gz"
tmp="/tmp/eza.tar.gz"
echo 'Downloading newset version'
curl -L -o $tmp $url
echo 'Installing newest version'
sudo tar -xf $tmp -C /usr/bin ./eza
echo 'Cleaning up'
rm -rf $tmp
echo 'Done'
