#!/bin/sh

set -e

if ! command -v curl > /dev/null 2>&1; then
  echo 'No curl found'
  exit 1
fi

url="https://github.com/sharkdp/bat/releases/download/v0.26.0/bat-v0.26.0-x86_64-unknown-linux-gnu.tar.gz"
tmp="/tmp/bat.tar.gz"
echo 'Downloading newset version'
curl -L -o $tmp $url
echo 'Installing newest version'
sudo tar -xf $tmp -C /usr/bin --strip-components=1 bat-v0.26.0-x86_64-unknown-linux-gnu/bat
echo 'Cleaning up'
rm -rf $tmp
echo 'Done'
