#!/bin/sh

set -e

if ! command -v curl > /dev/null 2>&1; then
  echo 'No curl found'
  exit 1
fi

url="https://github.com/junegunn/fzf/releases/download/v0.62.0/fzf-0.62.0-linux_amd64.tar.gz"
tmp="/tmp/fzf.tar.gz"
echo 'Downloading newset version'
curl -L -o $tmp $url
echo 'Installing newest version'
sudo tar -xf $tmp -C /usr/bin fzf
echo 'Cleaning up'
rm -rf $tmp
echo 'Done'
